kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: details-v1
  namespace: bookinfo
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: details
        version: v1
    spec:
      containers:
        - name: details
          image: 'docker.io/istio/examples-bookinfo-details-v1:1.15.0'
          ports:
            - containerPort: 9080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:  
              command: 
              - cat
              - /tmp/healthy
            periodSeconds: 10 
            successThreshold: 1 
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
